version: "3.0"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432

  storage_bucket:
    image: struckchure/file_storage:latest
    ports:
      - 1276:1276

  api:
    build:
      context: .
      dockerfile: ${PWD}/.docker/python/Dockerfile
    volumes:
      - .:/home/e_commerce_user
      - pip_site_packges:/usr/local/lib/python3.10/site-packages
      - pip_cache:/home/e_commerce_user/.cache/pip
    command: python manage.py runserver 0.0.0.0:${PORT}
    env_file:
      - .env
    depends_on:
      - db
      - storage_bucket
    ports:
      - ${PORT}:${PORT}

volumes:
  db_data:
  pip_site_packges:
  pip_cache:
