version: "3.0"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
  # api:
  #   build:
  #     context: .
  #     dockerfile: ${PWD}/.docker/python/Dockerfile
  #   volumes:
  #     - .:/home/e_commerce
  #   command: python manage.py runserver 0.0.0.0:${PORT}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   ports:
  #     - ${PORT}:${PORT}

volumes:
  db_data:
