# Generated by Django 4.1.3 on 2022-11-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_category_product_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
