# Generated by Django 4.1.3 on 2022-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_wallet_transaction_paymentplatform_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(default="3E16392E29A40904", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentplatform",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="paymentplatform",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(default="02066D406EF14F71", max_length=50),
        ),
    ]
