# Generated by Django 4.1.3 on 2022-11-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_paymentplatform_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="platform_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(default="BC1D7AF703094338", max_length=50),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(default="FA63EF47F3AA1EAF", max_length=50),
        ),
    ]
