# Generated by Django 4.1.3 on 2022-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_transaction_platform_reference_alter_order_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(default="E53737241B35E91D", max_length=50),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(default="EC0FBFC911627436", max_length=50),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESSFUL", "Successful"),
                    ("PENDING", "Pending"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
