# Generated by Django 4.1.3 on 2022-11-29 23:27

from django.db import migrations, models
import e_commerce.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_order_reference_alter_transaction_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(
                default=e_commerce.utils.generate_reference, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                default=e_commerce.utils.generate_reference, max_length=50
            ),
        ),
    ]
