# Generated by Django 4.1.3 on 2022-11-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_order_reference_alter_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.transaction",
            ),
        ),
    ]
